---
- name: Raspberry Pi Configuration
  hosts: pi_nodes
  roles:
    - role: common
      tags: [common, base]

    - role: network
      tags: [network]

    - role: printServer
      tags: [print]

    - role: chezmoi
      tags: [chezmoi, dotfiles]
