---
# roles/roon/meta/main.yml

galaxy_info:
  role_name: roon
  author: bhdicaire
  description: Install and configure Roon Server on Debian
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions:
        - bookworm
        - trixie

dependencies:
  - role: common
