---

# Printers should match the 'lpinfo -v | grep usb' output
dymo_usb_uri: "usb://DYMO/LabelWriter%20Twin%20Turbo?serial=%3f%3f%3f%3f%3f%3f%3f%3f%3f%3f%3f%3f%3f%3f"
dymo_ppd: "dymo:0/cups/model/lwtt.ppd"

brother_usb_uri: "usb://Brother/PT-P700?serial=000E8Z343235"
brother_ppd: "ptouch:0/ppd/ptouch-driver/Brother-PT-P700-ptouch-pt.ppd"

network_setup:
  method: manual
  ip_address: "172.30.80.22/24"
  gateway: "172.30.80.1"
  vlan_gateway: "172.30.80.1"
  dns_servers:
    - "172.30.80.1"
  route_metric: 10
  native_method: disabled
  vlan_interface: eth0
  vlan_id: 80
  vlan_name: "eth0.80"
