---

# Printers via 'lpinfo -v | grep usb'
brother_usb_uri: "usb://Brother/PT-P700?serial=000E8Z343235"
dymo_usb_uri: "usb://DYMO/LabelWriter%20Twin%20Turbo?serial=%3f%3f%3f%3f%3f%3f%3f%3f%3f%3f%3f%3f%3f%3f"

# Network
vlan: 80
network_ip: "dhcp" # IP must match the Unifi DHCP reservation for MAC identified below
network_mac: "38:05:25:37:22:b2" # NIC MAC addresses (from: sudo lspci -nn + ip link show)
